name: ShortSneak
version: 1.1.1
src-namespace-prefix: DavyCraft648\ShortSneak
main: DavyCraft648\ShortSneak\Main
api: 5.0.0
description: "Sneak 1.5 block like in Minecraft: Java Edition"
author: DavyCraft648
website: https://github.com/DavyCraft648/ShortSneak
